import csv
from datetime import datetime
from io import BytesIO, StringIO

from flask import make_response
from openpyxl import Workbook
from openpyxl.styles import Font


def _value(value):
    if value is None:
        return "N/A"
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M:%S")
    return value


def build_report_response(
    title, generated_by, filters, columns, rows, file_format, filename
):
    metadata = [
        ["Report Name", title],
        ["Generated By", generated_by],
        ["Generated Date", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Date Range", filters.get("date_range", "Default report period")],
        ["Applied Filters", filters.get("applied", "None")],
    ]
    if file_format == "csv":
        output = StringIO()
        writer = csv.writer(output)
        writer.writerows(metadata)
        writer.writerow([])
        writer.writerow(columns)
        writer.writerows(
            [[_value(row.get(column)) for column in columns] for row in rows]
        )
        response = make_response(output.getvalue())
        response.mimetype = "text/csv"
    elif file_format == "xlsx":
        workbook = Workbook()
        sheet = workbook.active
        sheet.title = "Report"
        for row in metadata:
            sheet.append(row)
        sheet.append([])
        sheet.append(columns)
        for cell in sheet[sheet.max_row]:
            cell.font = Font(bold=True)
        for row in rows:
            sheet.append([_value(row.get(column)) for column in columns])
        sheet.freeze_panes = "A8"
        output = BytesIO()
        workbook.save(output)
        response = make_response(output.getvalue())
        response.mimetype = (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    else:
        raise ValueError("Unsupported export format")
    response.headers["Content-Disposition"] = (
        f'attachment; filename="{filename}.{file_format}"'
    )
    return response
