"""align unique identifier indexes

Revision ID: 107cf26be775
Revises: 26a6ed07ee2f
Create Date: 2026-09-03 18:53:11.730109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107cf26be775'
down_revision = '26a6ed07ee2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_commissions_commission_number'))
        batch_op.create_index(batch_op.f('ix_property_commissions_commission_number'), ['commission_number'], unique=True)

    with op.batch_alter_table('property_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_transactions_transaction_number'))
        batch_op.create_index(batch_op.f('ix_property_transactions_transaction_number'), ['transaction_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_transactions_transaction_number'))
        batch_op.create_index(batch_op.f('ix_property_transactions_transaction_number'), ['transaction_number'], unique=False)

    with op.batch_alter_table('property_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_commissions_commission_number'))
        batch_op.create_index(batch_op.f('ix_property_commissions_commission_number'), ['commission_number'], unique=False)

    # ### end Alembic commands ###
