"""create viewing requests

Revision ID: 398f3945eafd
Revises: p4q5r6s7t8u9
Create Date: 2026-09-03 17:19:09.158368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398f3945eafd'
down_revision = 'p4q5r6s7t8u9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=30), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viewing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viewing_requests_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_requests_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_requests_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_viewing_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewing_requests_status'))
        batch_op.drop_index(batch_op.f('ix_viewing_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_viewing_requests_property_id'))
        batch_op.drop_index(batch_op.f('ix_viewing_requests_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_viewing_requests_agent_id'))

    op.drop_table('viewing_requests')
    # ### end Alembic commands ###
